//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyMusicCloud.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MusicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyMusicCloud.Resource.MusicResource", typeof(MusicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string AlbumHeader {
            get {
                return ResourceManager.GetString("AlbumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album : {0}.
        /// </summary>
        public static string AlbumTab {
            get {
                return ResourceManager.GetString("AlbumTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArtistHeader {
            get {
                return ResourceManager.GetString("ArtistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist : {0}.
        /// </summary>
        public static string ArtistTab {
            get {
                return ResourceManager.GetString("ArtistTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseHeader {
            get {
                return ResourceManager.GetString("BrowseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DowloadToolTip {
            get {
                return ResourceManager.GetString("DowloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All.
        /// </summary>
        public static string DownloadAllHeader {
            get {
                return ResourceManager.GetString("DownloadAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Download : {0}.
        /// </summary>
        public static string DownloadSongTask {
            get {
                return ResourceManager.GetString("DownloadSongTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string LibraryMenu {
            get {
                return ResourceManager.GetString("LibraryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathHeader {
            get {
                return ResourceManager.GetString("PathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play all.
        /// </summary>
        public static string PlayAllHeader {
            get {
                return ResourceManager.GetString("PlayAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayToolTip {
            get {
                return ResourceManager.GetString("PlayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search : {0}.
        /// </summary>
        public static string SearchTab {
            get {
                return ResourceManager.GetString("SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string SongToolTip {
            get {
                return ResourceManager.GetString("SongToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateHeader {
            get {
                return ResourceManager.GetString("StateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskHeader {
            get {
                return ResourceManager.GetString("TaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string UploadMenu {
            get {
                return ResourceManager.GetString("UploadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Upload : {0}.
        /// </summary>
        public static string UploadSongTask {
            get {
                return ResourceManager.GetString("UploadSongTask", resourceCulture);
            }
        }
    }
}
