//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyMusicCloud.Client.Service.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Proxy.IMusicService")]
    public interface IMusicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetAllSongs", ReplyAction="http://tempuri.org/IMusicService/GetAllSongsResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetAllSongs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/SearchSongs", ReplyAction="http://tempuri.org/IMusicService/SearchSongsResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> SearchSongs(string filter, bool onTitle, bool onArtist, bool onAlbum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/AddASong", ReplyAction="http://tempuri.org/IMusicService/AddASongResponse")]
        void AddASong(MonkeyMusicCloud.Domain.Model.Song song, MonkeyMusicCloud.Domain.Model.MediaFile mediaFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetByAlbum", ReplyAction="http://tempuri.org/IMusicService/GetByAlbumResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetByAlbum(string album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetMediaFileById", ReplyAction="http://tempuri.org/IMusicService/GetMediaFileByIdResponse")]
        MonkeyMusicCloud.Domain.Model.MediaFile GetMediaFileById(System.Guid mediaFileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetAlbumsByArtist", ReplyAction="http://tempuri.org/IMusicService/GetAlbumsByArtistResponse")]
        System.Collections.ObjectModel.ObservableCollection<string> GetAlbumsByArtist(string artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetByArtist", ReplyAction="http://tempuri.org/IMusicService/GetByArtistResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetByArtist(string artist);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusicServiceChannel : MonkeyMusicCloud.Client.Service.Proxy.IMusicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicServiceClient : System.ServiceModel.ClientBase<MonkeyMusicCloud.Client.Service.Proxy.IMusicService>, MonkeyMusicCloud.Client.Service.Proxy.IMusicService {
        
        public MusicServiceClient() {
        }
        
        public MusicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetAllSongs() {
            return base.Channel.GetAllSongs();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> SearchSongs(string filter, bool onTitle, bool onArtist, bool onAlbum) {
            return base.Channel.SearchSongs(filter, onTitle, onArtist, onAlbum);
        }
        
        public void AddASong(MonkeyMusicCloud.Domain.Model.Song song, MonkeyMusicCloud.Domain.Model.MediaFile mediaFile) {
            base.Channel.AddASong(song, mediaFile);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetByAlbum(string album) {
            return base.Channel.GetByAlbum(album);
        }
        
        public MonkeyMusicCloud.Domain.Model.MediaFile GetMediaFileById(System.Guid mediaFileId) {
            return base.Channel.GetMediaFileById(mediaFileId);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> GetAlbumsByArtist(string artist) {
            return base.Channel.GetAlbumsByArtist(artist);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetByArtist(string artist) {
            return base.Channel.GetByArtist(artist);
        }
    }
}
