//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyMusicCloud.Client.Service.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Proxy.IMusicService")]
    public interface IMusicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetAllSongs", ReplyAction="http://tempuri.org/IMusicService/GetAllSongsResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetAllSongs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/SearchSongs", ReplyAction="http://tempuri.org/IMusicService/SearchSongsResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> SearchSongs(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/AddASong", ReplyAction="http://tempuri.org/IMusicService/AddASongResponse")]
        void AddASong(MonkeyMusicCloud.Domain.Model.Song song);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicService/GetByAlbum", ReplyAction="http://tempuri.org/IMusicService/GetByAlbumResponse")]
        System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetByAlbum(string album);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusicServiceChannel : MonkeyMusicCloud.Client.Service.Proxy.IMusicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicServiceClient : System.ServiceModel.ClientBase<MonkeyMusicCloud.Client.Service.Proxy.IMusicService>, MonkeyMusicCloud.Client.Service.Proxy.IMusicService {
        
        public MusicServiceClient() {
        }
        
        public MusicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetAllSongs() {
            return base.Channel.GetAllSongs();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> SearchSongs(string filter) {
            return base.Channel.SearchSongs(filter);
        }
        
        public void AddASong(MonkeyMusicCloud.Domain.Model.Song song) {
            base.Channel.AddASong(song);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MonkeyMusicCloud.Domain.Model.Song> GetByAlbum(string album) {
            return base.Channel.GetByAlbum(album);
        }
    }
}
